### ISSUE TITLE
[Meet] 20170212 线上会议

### ISSUE THREAD

**Issue by TheThinkerGroup** [TheThinkerGroup/IntellectualClub#1]

**Comment by asiachrispy** [comment]
明天的会议，我先给出下列建议，待明天讨论

- 1. 管理建议使用工具，参考之前的建议
- 2. 固定的内容要体现，多余的信息不限制
- 3. 每个人可以选多本书。选择图书，提交读书笔记，评比读书笔记，选取TOP3的笔记，不一定要综合。
- 4. 如何协助会员自主完成主题阅读材料的选择是更重要的问题。主题阅读的目的，通过广度优先阅读目构建主题知识框架，通过深度优先阅读完成框架知识的填补，主题阅读的原理是利用大脑善于对比学习。
- 5. 线上兴趣小组越少越好，建议发起线下主题活动，更容易产生情感连接。
- 6. 寻找自愿分享会员，并邀请有经验会员分享，分享前审核内容质量，给出建议。
- 7. 活动可以再找一些自愿者，让会员参与进来，自构建社群系统的进化

主题和书单是否还要讨论？
